"""Auto-generated EDSDK constants.

Generated by ``tools/gen_constants.py`` from
``EDSDKTypes.h``. Do not edit by hand — re-run the
generator instead.
"""

from __future__ import annotations

from enum import IntEnum


class PropID(IntEnum):
    Unknown = 0x0000FFFF
    ProductName = 0x00000002
    OwnerName = 0x00000004
    MakerName = 0x00000005
    DateTime = 0x00000006
    FirmwareVersion = 0x00000007
    BatteryLevel = 0x00000008
    SaveTo = 0x0000000B
    CurrentStorage = 0x0000000C
    CurrentFolder = 0x0000000D
    BatteryQuality = 0x00000010
    BodyIDEx = 0x00000015
    HDDirectoryStructure = 0x00000020
    ImageQuality = 0x00000100
    Orientation = 0x00000102
    ICCProfile = 0x00000103
    FocusInfo = 0x00000104
    WhiteBalance = 0x00000106
    ColorTemperature = 0x00000107
    WhiteBalanceShift = 0x00000108
    ColorSpace = 0x0000010D
    PictureStyle = 0x00000114
    PictureStyleDesc = 0x00000115
    PictureStyleCaption = 0x00000200
    GPSVersionID = 0x00000800
    GPSLatitudeRef = 0x00000801
    GPSLatitude = 0x00000802
    GPSLongitudeRef = 0x00000803
    GPSLongitude = 0x00000804
    GPSAltitudeRef = 0x00000805
    GPSAltitude = 0x00000806
    GPSTimeStamp = 0x00000807
    GPSSatellites = 0x00000808
    GPSStatus = 0x00000809
    GPSMapDatum = 0x00000812
    GPSDateStamp = 0x0000081D
    AEMode = 0x00000400
    DriveMode = 0x00000401
    ISOSpeed = 0x00000402
    MeteringMode = 0x00000403
    AFMode = 0x00000404
    Av = 0x00000405
    Tv = 0x00000406
    ExposureCompensation = 0x00000407
    FocalLength = 0x00000409
    AvailableShots = 0x0000040A
    Bracket = 0x0000040B
    WhiteBalanceBracket = 0x0000040C
    LensName = 0x0000040D
    AEBracket = 0x0000040E
    FEBracket = 0x0000040F
    ISOBracket = 0x00000410
    NoiseReduction = 0x00000411
    FlashOn = 0x00000412
    RedEye = 0x00000413
    FlashMode = 0x00000414
    LensStatus = 0x00000416
    Artist = 0x00000418
    Copyright = 0x00000419
    AEModeSelect = 0x00000436
    PowerZoom_Speed = 0x00000444
    ColorFilter = 0x0000047F
    DigitalZoomSetting = 0x00000477
    AfLockState = 0x00000480
    BrightnessSetting = 0x00000483
    IBIS_HighResoShot = 0x000004E0
    StillFileNameSetting = 0x000004E1
    StillFileNameUserSet1 = 0x000004E2
    StillFileNameUserSet2 = 0x000004E3
    StillFolderName = 0x000004E4
    MovieFileNameIndex = 0x000004E5
    MovieFileNameReelNo = 0x000004E6
    MovieFileNameClipNo = 0x000004E7
    MovieFileNameUserDef = 0x000004E8
    Evf_OutputDevice = 0x00000500
    Evf_Mode = 0x00000501
    Evf_WhiteBalance = 0x00000502
    Evf_ColorTemperature = 0x00000503
    Evf_DepthOfFieldPreview = 0x00000504
    Evf_Zoom = 0x00000507
    Evf_ZoomPosition = 0x00000508
    Evf_Histogram = 0x0000050A
    Evf_ImagePosition = 0x0000050B
    Evf_HistogramStatus = 0x0000050C
    Evf_AFMode = 0x0000050E
    Record = 0x00000510
    Evf_HistogramY = 0x00000515
    Evf_HistogramR = 0x00000516
    Evf_HistogramG = 0x00000517
    Evf_HistogramB = 0x00000518
    Evf_CoordinateSystem = 0x00000540
    Evf_ZoomRect = 0x00000541
    Evf_ImageClipRect = 0x00000545
    Evf_PowerZoom_CurPosition = 0x00000550
    Evf_PowerZoom_MaxPosition = 0x00000551
    Evf_PowerZoom_MinPosition = 0x00000552
    UTCTime = 0x01000016
    TimeZone = 0x01000017
    SummerTimeSetting = 0x01000018
    ManualWhiteBalanceData = 0x01000204
    TempStatus = 0x01000415
    MirrorLockUpState = 0x01000421
    FixedMovie = 0x01000422
    MovieParam = 0x01000423
    Aspect = 0x01000431
    ContinuousAfMode = 0x01000433
    MirrorUpSetting = 0x01000438
    MovieServoAf = 0x0100043E
    AutoPowerOffSetting = 0x0100045E
    AFEyeDetect = 0x01000455
    FocusShiftSetting = 0x01000457
    MovieHFRSetting = 0x0100045D
    AFTrackingObject = 0x01000468
    RegisterFocusEdge = 0x0100046C
    DriveFocusToEdge = 0x0100046D
    FocusPosition = 0x0100046E
    StillMovieDivideSetting = 0x01000470
    CardExtension = 0x01000471
    MovieCardExtension = 0x01000472
    StillCurrentMedia = 0x01000473
    MovieCurrentMedia = 0x01000474
    ApertureLockSetting = 0x01000476
    LensIsSetting = 0x010004C0
    ScreenDimmerTime = 0x010004C1
    ScreenOffTime = 0x010004C2
    ViewfinderOffTime = 0x010004C3
    Evf_ClickWBCoeffs = 0x01000506
    Evf_ViewType = 0x01000513
    EVF_RollingPitching = 0x01000544
    Evf_VisibleRect = 0x01000546
    Evf_FocalLength = 0x01000555
    MovieRecVolume_IntMic = 0x01000489
    MovieRecVolume_ExtMic = 0x0100048A
    MovieRecVolume_Acc = 0x0100048B
    MovieParamEx = 0x011004C6
    SlowFastMode = 0x010004C7
    Flash_Firing = 0x0000200D
    Flash_Target = 0x0000201E
    DC_Zoom = 0x00000600
    DC_Strobe = 0x00000601
    LensBarrelStatus = 0x00000605


class CameraCommand(IntEnum):
    TakePicture = 0x00000000
    ExtendShutDownTimer = 0x00000001
    BulbStart = 0x00000002
    BulbEnd = 0x00000003
    DoEvfAf = 0x00000102
    DriveLensEvf = 0x00000103
    DoClickWBEvf = 0x00000104
    MovieSelectSwON = 0x00000107
    MovieSelectSwOFF = 0x00000108
    PressShutterButton = 0x00000004
    RequestRollPitchLevel = 0x00000109
    DrivePowerZoom = 0x0000010D
    SetRemoteShootingMode = 0x0000010F
    RequestSensorCleaning = 0x00000112
    SetModeDialDisable = 0x00000113


class CameraStatusCommand(IntEnum):
    UILock = 0x00000000
    UIUnLock = 0x00000001
    EnterDirectTransfer = 0x00000002
    ExitDirectTransfer = 0x00000003


class ObjectEvent(IntEnum):
    All = 0x00000200
    VolumeInfoChanged = 0x00000201
    VolumeUpdateItems = 0x00000202
    FolderUpdateItems = 0x00000203
    DirItemCreated = 0x00000204
    DirItemRemoved = 0x00000205
    DirItemInfoChanged = 0x00000206
    DirItemContentChanged = 0x00000207
    DirItemRequestTransfer = 0x00000208
    DirItemRequestTransferDT = 0x00000209
    DirItemCancelTransferDT = 0x0000020A
    VolumeAdded = 0x0000020C
    VolumeRemoved = 0x0000020D


class PropertyEvent(IntEnum):
    All = 0x00000100
    PropertyChanged = 0x00000101
    PropertyDescChanged = 0x00000102
    PropertyDescExChanged = 0x00000110


class StateEvent(IntEnum):
    All = 0x00000300
    Shutdown = 0x00000301
    JobStatusChanged = 0x00000302
    WillSoonShutDown = 0x00000303
    ShutDownTimerUpdate = 0x00000304
    CaptureError = 0x00000305
    InternalError = 0x00000306
    AfResult = 0x00000309
    BulbExposureTime = 0x00000310
    PowerZoomInfoChanged = 0x00000311


class AEMode(IntEnum):
    Program = 0x00000000
    Tv = 0x00000001
    Av = 0x00000002
    Manual = 0x00000003
    Bulb = 0x00000004
    A_DEP = 0x00000005
    DEP = 0x00000006
    Custom = 0x00000007
    Lock = 0x00000008
    Green = 0x00000009
    NightPortrait = 0x0000000A
    Sports = 0x0000000B
    Portrait = 0x0000000C
    Landscape = 0x0000000D
    Closeup = 0x0000000E
    FlashOff = 0x0000000F
    CreativeAuto = 0x00000013
    Movie = 0x00000014
    PhotoInMovie = 0x00000015
    SceneIntelligentAuto = 0x00000016
    SCN = 0x00000019
    NightScenes = 0x00000017
    BacklitScenes = 0x00000018
    Children = 0x0000001A
    Food = 0x0000001B
    CandlelightPortraits = 0x0000001C
    CreativeFilter = 0x0000001D
    RoughMonoChrome = 0x0000001E
    SoftFocus = 0x0000001F
    ToyCamera = 0x00000020
    Fisheye = 0x00000021
    WaterColor = 0x00000022
    Miniature = 0x00000023
    Hdr_Standard = 0x00000024
    Hdr_Vivid = 0x00000025
    Hdr_Bold = 0x00000026
    Hdr_Embossed = 0x00000027
    Movie_Fantasy = 0x00000028
    Movie_Old = 0x00000029
    Movie_Memory = 0x0000002A
    Movie_DirectMono = 0x0000002B
    Movie_Mini = 0x0000002C
    PanningAssist = 0x0000002D
    GroupPhoto = 0x0000002E
    Myself = 0x00000032
    PlusMovieAuto = 0x00000033
    SmoothSkin = 0x00000034
    Panorama = 0x00000035
    Silent = 0x00000036
    Flexible = 0x00000037
    OilPainting = 0x00000038
    Fireworks = 0x00000039
    StarPortrait = 0x0000003A
    StarNightscape = 0x0000003B
    StarTrails = 0x0000003C
    StarTimelapseMovie = 0x0000003D
    BackgroundBlur = 0x0000003E
    VideoBlog = 0x0000003F
    Unknown = 0xFFFFFFFF


class Access(IntEnum):
    Read = 0x00000000
    Write = 0x00000001
    ReadWrite = 0x00000002
    Error = 0xFFFFFFFF


class BatteryLevel2(IntEnum):
    Empty = 0x00000000
    Low = 0x00000009
    Half = 0x00000031
    Normal = 0x00000050
    Hi = 0x00000045
    Quarter = 0x00000013
    Error = 0x00000000
    BCLevel = 0x00000000
    AC = 0xFFFFFFFF
    Unknown = 0xFFFFFFFE


class Bracket(IntEnum):
    AEB = 0x00000001
    ISOB = 0x00000002
    WBB = 0x00000004
    FEB = 0x00000008
    Unknown = 0xFFFFFFFF


class ColorSpace(IntEnum):
    sRGB = 0x00000001
    AdobeRGB = 0x00000002
    Unknown = 0xFFFFFFFF


class CompressQuality(IntEnum):
    Normal = 0x00000002
    Fine = 0x00000003
    Lossless = 0x00000004
    SuperFine = 0x00000005
    Unknown = 0xFFFFFFFF


class DataType(IntEnum):
    Unknown = 0x00000000
    Bool = 0x00000001
    String = 0x00000002
    Int8 = 0x00000003
    UInt8 = 0x00000006
    Int16 = 0x00000004
    UInt16 = 0x00000007
    Int32 = 0x00000008
    UInt32 = 0x00000009
    Int64 = 0x0000000A
    UInt64 = 0x0000000B
    Float = 0x0000000C
    Double = 0x0000000D
    ByteBlock = 0x0000000E
    Rational = 0x00000014
    Point = 0x00000015
    Rect = 0x00000016
    Time = 0x00000017
    Bool_Array = 0x0000001E
    Int8_Array = 0x0000001F
    Int16_Array = 0x00000020
    Int32_Array = 0x00000021
    UInt8_Array = 0x00000022
    UInt16_Array = 0x00000023
    UInt32_Array = 0x00000024
    Rational_Array = 0x00000025
    FocusInfo = 0x00000065
    PictureStyleDesc = 0x00000066


class DcLensBarrelState(IntEnum):
    Inner = 0x00000000
    Outer = 0x00000001


class DcRemoteShootingMode(IntEnum):
    Stop = 0x00000000
    Start = 0x00000001


class DcStrobe(IntEnum):
    Auto = 0x00000000
    On = 0x00000001
    Slowsynchro = 0x00000002
    Off = 0x00000003


class DrivePowerZoom(IntEnum):
    Stop = 0x00000000
    LimitOff_Wide = 0x00000001
    LimitOff_Tele = 0x00000002
    LimitOn_Wide = 0x00000011
    LimitOn_Tele = 0x00000012


class ETTL2Mode(IntEnum):
    Evaluative = 0x00000000
    Average = 0x00000001


class EvfAFMode(IntEnum):
    Quick = 0x00000000
    Live = 0x00000001
    LiveFace = 0x00000002
    LiveMulti = 0x00000003
    LiveZone = 0x00000004
    LiveSingleExpandCross = 0x00000005
    LiveSingleExpandAround = 0x00000006
    LiveZoneLargeH = 0x00000007
    LiveZoneLargeV = 0x00000008
    LiveCatchAF = 0x00000009
    LiveSpotAF = 0x0000000A
    FlexibleZone1 = 0x0000000B
    FlexibleZone2 = 0x0000000C
    FlexibleZone3 = 0x0000000D
    WholeArea = 0x0000000E
    NoTraking_Spot = 0x0000000F
    NoTraking_1Point = 0x00000010
    NoTraking_ExpandCross = 0x00000011
    NoTraking_ExpandAround = 0x00000012


class EvfAf(IntEnum):
    OFF = 0x00000000
    ON = 0x00000001


class EvfDepthOfFieldPreview(IntEnum):
    OFF = 0x00000000
    ON = 0x00000001


class EvfDriveLens(IntEnum):
    Near1 = 0x00000001
    Near2 = 0x00000002
    Near3 = 0x00000003
    Far1 = 0x00008001
    Far2 = 0x00008002
    Far3 = 0x00008003


class EvfOutputDevice(IntEnum):
    TFT = 0x00000001
    PC = 0x00000002
    PC_Small = 0x00000008


class EvfZoom(IntEnum):
    Fit = 0x00000001
    x5 = 0x00000005
    x6 = 0x00000006
    x10 = 0x0000000A
    x15 = 0x0000000F


class FileAttributes(IntEnum):
    Normal = 0x00000000
    ReadOnly = 0x00000001
    Hidden = 0x00000002
    System = 0x00000004
    Archive = 0x00000020


class FileCreateDisposition(IntEnum):
    CreateNew = 0x00000000
    CreateAlways = 0x00000001
    OpenExisting = 0x00000002
    OpenAlways = 0x00000003
    TruncateExsisting = 0x00000004


class ImageQuality(IntEnum):
    LJ = 0x0010FF0F
    MJ = 0x0110FF0F
    M1J = 0x0510FF0F
    M1F = 0x0513FF0F
    M1N = 0x0512FF0F
    M2J = 0x0610FF0F
    M2F = 0x0613FF0F
    M2N = 0x0612FF0F
    SJ = 0x0210FF0F
    S1J = 0x0E10FF0F
    S2J = 0x0F10FF0F
    LJF = 0x0013FF0F
    LJN = 0x0012FF0F
    MJF = 0x0113FF0F
    MJN = 0x0112FF0F
    SJF = 0x0213FF0F
    SJN = 0x0212FF0F
    S1JF = 0x0E13FF0F
    S1JN = 0x0E12FF0F
    S2JF = 0x0F13FF0F
    S3JF = 0x1013FF0F
    LR = 0x0064FF0F
    LRLJF = 0x00640013
    LRLJN = 0x00640012
    LRMJF = 0x00640113
    LRMJN = 0x00640112
    LRSJF = 0x00640213
    LRSJN = 0x00640212
    LRS1JF = 0x00640E13
    LRS1JN = 0x00640E12
    LRS2JF = 0x00640F13
    LRS3JF = 0x00641013
    LRLJ = 0x00640010
    LRMJ = 0x00640110
    LRM1J = 0x00640510
    LRM1F = 0x00640513
    LRM1N = 0x00640512
    LRM2J = 0x00640610
    LRM2F = 0x00640613
    LRM2N = 0x00640612
    LRSJ = 0x00640210
    LRS1J = 0x00640E10
    LRS2J = 0x00640F10
    MR = 0x0164FF0F
    MRLJF = 0x01640013
    MRLJN = 0x01640012
    MRMJF = 0x01640113
    MRMJN = 0x01640112
    MRSJF = 0x01640213
    MRSJN = 0x01640212
    MRS1JF = 0x01640E13
    MRS1JN = 0x01640E12
    MRS2JF = 0x01640F13
    MRS3JF = 0x01641013
    MRLJ = 0x01640010
    MRM1J = 0x01640510
    MRM1F = 0x01640513
    MRM1N = 0x01640512
    MRM2J = 0x01640610
    MRM2F = 0x01640613
    MRM2N = 0x01640612
    MRSJ = 0x01640210
    SR = 0x0264FF0F
    SRLJF = 0x02640013
    SRLJN = 0x02640012
    SRMJF = 0x02640113
    SRMJN = 0x02640112
    SRSJF = 0x02640213
    SRSJN = 0x02640212
    SRS1JF = 0x02640E13
    SRS1JN = 0x02640E12
    SRS2JF = 0x02640F13
    SRS3JF = 0x02641013
    SRLJ = 0x02640010
    SRM1J = 0x02640510
    SRM1F = 0x02640513
    SRM1N = 0x02640512
    SRM2J = 0x02640610
    SRM2F = 0x02640613
    SRM2N = 0x02640612
    SRSJ = 0x02640210
    CR = 0x0063FF0F
    CRLJF = 0x00630013
    CRMJF = 0x00630113
    CRM1JF = 0x00630513
    CRM2JF = 0x00630613
    CRSJF = 0x00630213
    CRS1JF = 0x00630E13
    CRS2JF = 0x00630F13
    CRS3JF = 0x00631013
    CRLJN = 0x00630012
    CRMJN = 0x00630112
    CRM1JN = 0x00630512
    CRM2JN = 0x00630612
    CRSJN = 0x00630212
    CRS1JN = 0x00630E12
    CRLJ = 0x00630010
    CRMJ = 0x00630110
    CRM1J = 0x00630510
    CRM2J = 0x00630610
    CRSJ = 0x00630210
    CRS1J = 0x00630E10
    CRS2J = 0x00630F10
    HEIFL = 0x0080FF0F
    HEIFM = 0x0180FF0F
    HEIFM1 = 0x0580FF0F
    HEIFM2 = 0x0680FF0F
    HEIFLF = 0x0083FF0F
    HEIFLN = 0x0082FF0F
    HEIFMF = 0x0183FF0F
    HEIFMN = 0x0182FF0F
    HEIFS1 = 0x0E80FF0F
    HEIFS1F = 0x0E83FF0F
    HEIFS1N = 0x0E82FF0F
    HEIFS2 = 0x0F80FF0F
    HEIFS2F = 0x0F83FF0F
    RHEIFL = 0x00640080
    RHEIFLF = 0x00640083
    RHEIFLN = 0x00640082
    RHEIFM = 0x00640180
    RHEIFM1 = 0x00640580
    RHEIFM2 = 0x00640680
    RHEIFMF = 0x00640183
    RHEIFMN = 0x00640182
    RHEIFS1 = 0x00640E80
    RHEIFS1F = 0x00640E83
    RHEIFS1N = 0x00640E82
    RHEIFS2 = 0x00640F80
    RHEIFS2F = 0x00640F83
    CRHEIFL = 0x00630080
    CRHEIFLF = 0x00630083
    CRHEIFLN = 0x00630082
    CRHEIFM = 0x00630180
    CRHEIFMF = 0x00630183
    CRHEIFMN = 0x00630182
    CRHEIFM1 = 0x00630580
    CRHEIFM2 = 0x00630680
    CRHEIFS1 = 0x00630E80
    CRHEIFS1F = 0x00630E83
    CRHEIFS1N = 0x00630E82
    CRHEIFS2 = 0x00630F80
    CRHEIFS2F = 0x00630F83
    Unknown = 0xFFFFFFFF


class ImageSize(IntEnum):
    Large = 0x00000000
    Middle = 0x00000001
    Small = 0x00000002
    Middle1 = 0x00000005
    Middle2 = 0x00000006
    Small1 = 0x0000000E
    Small2 = 0x0000000F
    Small3 = 0x00000010
    Unknown = 0xFFFFFFFF


class ImageSource(IntEnum):
    FullView = 0x00000000
    Thumbnail = 0x00000001
    Preview = 0x00000002
    RAWThumbnail = 0x00000003
    RAWFullView = 0x00000004


class ImageType(IntEnum):
    Unknown = 0x00000000
    Jpeg = 0x00000001
    CRW = 0x00000002
    RAW = 0x00000004
    CR2 = 0x00000006
    HEIF = 0x00000008


class MirrorLockupState(IntEnum):
    Disable = 0x00000000
    Enable = 0x00000001
    DuringShooting = 0x00000002


class MirrorUpSetting(IntEnum):
    Off = 0x00000000
    On = 0x00000001


class ObjectFormat(IntEnum):
    Unknown = 0x00000000
    Jpeg = 0x00003801
    CR2 = 0x0000B103
    MP4 = 0x0000B982
    CR3 = 0x0000B108
    HEIF_CODE = 0x0000B10B


class PictureStyle(IntEnum):
    Standard = 0x00000081
    Portrait = 0x00000082
    Landscape = 0x00000083
    Neutral = 0x00000084
    Faithful = 0x00000085
    Monochrome = 0x00000086
    Auto = 0x00000087
    FineDetail = 0x00000088
    User1 = 0x00000021
    User2 = 0x00000022
    User3 = 0x00000023
    PC1 = 0x00000041
    PC2 = 0x00000042
    PC3 = 0x00000043


class ProgressOption(IntEnum):
    NoReport = 0x00000000
    Done = 0x00000001
    Periodically = 0x00000002


class SaveTo(IntEnum):
    Camera = 0x00000001
    Host = 0x00000002
    Both = 0x00000003


class SeekOrigin(IntEnum):
    Cur = 0x00000000
    Begin = 0x00000001
    End = 0x00000002


class ShutterButton(IntEnum):
    OFF = 0x00000000
    Halfway = 0x00000001
    Completely = 0x00000003
    Halfway_NonAF = 0x00010001
    Completely_NonAF = 0x00010003


class StorageType(IntEnum):
    Non = 0x00000000
    CF = 0x00000001
    SD = 0x00000002
    HD = 0x00000004
    CFast = 0x00000005
    CFe = 0x00000007


class StroboMode(IntEnum):
    Internal = 0x00000000
    ExternalETTL = 0x00000001
    ExternalATTL = 0x00000002
    ExternalTTL = 0x00000003
    ExternalAuto = 0x00000004
    ExternalManual = 0x00000005
    Manual = 0x00000006


class TargetImageType(IntEnum):
    Unknown = 0x00000000
    Jpeg = 0x00000001
    TIFF = 0x00000007
    TIFF16 = 0x00000008
    RGB = 0x00000009
    RGB16 = 0x0000000A
    DIB = 0x0000000B


class TransferOption(IntEnum):
    ByDirectTransfer = 0x00000001
    ByRelease = 0x00000002
    ToDesktop = 0x00000100


class WhiteBalance(IntEnum):
    Auto = 0x00000000
    Daylight = 0x00000001
    Cloudy = 0x00000002
    Tungsten = 0x00000003
    Fluorescent = 0x00000004
    Strobe = 0x00000005
    WhitePaper = 0x00000006
    Shade = 0x00000008
    ColorTemp = 0x00000009
    PCSet1 = 0x0000000A
    PCSet2 = 0x0000000B
    PCSet3 = 0x0000000C
    WhitePaper2 = 0x0000000F
    WhitePaper3 = 0x00000010
    WhitePaper4 = 0x00000012
    WhitePaper5 = 0x00000013
    PCSet4 = 0x00000014
    PCSet5 = 0x00000015
    AwbWhite = 0x00000017
    Click = -1
    Pasted = -2


__all__ = [
    "AEMode",
    "Access",
    "BatteryLevel2",
    "Bracket",
    "CameraCommand",
    "CameraStatusCommand",
    "ColorSpace",
    "CompressQuality",
    "DataType",
    "DcLensBarrelState",
    "DcRemoteShootingMode",
    "DcStrobe",
    "DrivePowerZoom",
    "ETTL2Mode",
    "EvfAFMode",
    "EvfAf",
    "EvfDepthOfFieldPreview",
    "EvfDriveLens",
    "EvfOutputDevice",
    "EvfZoom",
    "FileAttributes",
    "FileCreateDisposition",
    "ImageQuality",
    "ImageSize",
    "ImageSource",
    "ImageType",
    "MirrorLockupState",
    "MirrorUpSetting",
    "ObjectEvent",
    "ObjectFormat",
    "PictureStyle",
    "ProgressOption",
    "PropID",
    "PropertyEvent",
    "SaveTo",
    "SeekOrigin",
    "ShutterButton",
    "StateEvent",
    "StorageType",
    "StroboMode",
    "TargetImageType",
    "TransferOption",
    "WhiteBalance",
]
